// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chaincodes/event/protos/event_log.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventLogHeaderProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	ChaincodeId   string                 `protobuf:"bytes,2,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	TxId          string                 `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLogHeaderProto) Reset() {
	*x = EventLogHeaderProto{}
	mi := &file_chaincodes_event_protos_event_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLogHeaderProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLogHeaderProto) ProtoMessage() {}

func (x *EventLogHeaderProto) ProtoReflect() protoreflect.Message {
	mi := &file_chaincodes_event_protos_event_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLogHeaderProto.ProtoReflect.Descriptor instead.
func (*EventLogHeaderProto) Descriptor() ([]byte, []int) {
	return file_chaincodes_event_protos_event_log_proto_rawDescGZIP(), []int{0}
}

func (x *EventLogHeaderProto) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *EventLogHeaderProto) GetChaincodeId() string {
	if x != nil {
		return x.ChaincodeId
	}
	return ""
}

func (x *EventLogHeaderProto) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

type EventLogProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *EventLogHeaderProto   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Elems         [][]byte               `protobuf:"bytes,2,rep,name=elems,proto3" json:"elems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLogProto) Reset() {
	*x = EventLogProto{}
	mi := &file_chaincodes_event_protos_event_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLogProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLogProto) ProtoMessage() {}

func (x *EventLogProto) ProtoReflect() protoreflect.Message {
	mi := &file_chaincodes_event_protos_event_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLogProto.ProtoReflect.Descriptor instead.
func (*EventLogProto) Descriptor() ([]byte, []int) {
	return file_chaincodes_event_protos_event_log_proto_rawDescGZIP(), []int{1}
}

func (x *EventLogProto) GetHeader() *EventLogHeaderProto {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EventLogProto) GetElems() [][]byte {
	if x != nil {
		return x.Elems
	}
	return nil
}

var File_chaincodes_event_protos_event_log_proto protoreflect.FileDescriptor

const file_chaincodes_event_protos_event_log_proto_rawDesc = "" +
	"\n" +
	"'chaincodes/event/protos/event_log.proto\x12\x05event\"l\n" +
	"\x13EventLogHeaderProto\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12!\n" +
	"\fchaincode_id\x18\x02 \x01(\tR\vchaincodeId\x12\x13\n" +
	"\x05tx_id\x18\x03 \x01(\tR\x04txId\"Y\n" +
	"\rEventLogProto\x122\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.event.EventLogHeaderProtoR\x06header\x12\x14\n" +
	"\x05elems\x18\x02 \x03(\fR\x05elemsB0Z.github.com/beatoz/bprn-sdk-go/chaincodes/eventb\x06proto3"

var (
	file_chaincodes_event_protos_event_log_proto_rawDescOnce sync.Once
	file_chaincodes_event_protos_event_log_proto_rawDescData []byte
)

func file_chaincodes_event_protos_event_log_proto_rawDescGZIP() []byte {
	file_chaincodes_event_protos_event_log_proto_rawDescOnce.Do(func() {
		file_chaincodes_event_protos_event_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chaincodes_event_protos_event_log_proto_rawDesc), len(file_chaincodes_event_protos_event_log_proto_rawDesc)))
	})
	return file_chaincodes_event_protos_event_log_proto_rawDescData
}

var file_chaincodes_event_protos_event_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chaincodes_event_protos_event_log_proto_goTypes = []any{
	(*EventLogHeaderProto)(nil), // 0: event.EventLogHeaderProto
	(*EventLogProto)(nil),       // 1: event.EventLogProto
}
var file_chaincodes_event_protos_event_log_proto_depIdxs = []int32{
	0, // 0: event.EventLogProto.header:type_name -> event.EventLogHeaderProto
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chaincodes_event_protos_event_log_proto_init() }
func file_chaincodes_event_protos_event_log_proto_init() {
	if File_chaincodes_event_protos_event_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chaincodes_event_protos_event_log_proto_rawDesc), len(file_chaincodes_event_protos_event_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chaincodes_event_protos_event_log_proto_goTypes,
		DependencyIndexes: file_chaincodes_event_protos_event_log_proto_depIdxs,
		MessageInfos:      file_chaincodes_event_protos_event_log_proto_msgTypes,
	}.Build()
	File_chaincodes_event_protos_event_log_proto = out.File
	file_chaincodes_event_protos_event_log_proto_goTypes = nil
	file_chaincodes_event_protos_event_log_proto_depIdxs = nil
}
